(in-package :2x0ng)

(defresource "navajo-1.wav")
(defresource "navajo-2.wav")
(defresource "navajo-3.wav")
(defresource "peach-1.wav")
(defresource "peach-2.wav")
(defresource "peach-3.wav")
(defresource "peach-4.wav")
(defresource "sandy-1.wav")

(defvar *peach* nil)
(defvar *navajo* nil)
(defvar *sandy* nil)

(defun play-movie ()
  (setf *peach* (new 'robot "peach puff"))
  (setf *navajo* (new 'robot "navajo white"))
  (setf *sandy* (new 'robot "sandy brown"))
  (switch-to-buffer (2x0ng-level 0))
  (insert *navajo* (units 10) (units 7))
  (insert *sandy* (units 7) (units 10))
  (insert *peach* (units 13) (units 10))
  (stop-dialogue))

(defun play-scene ()
  (say *navajo* "navajo-1.wav")
  (say *navajo* "navajo-2.wav")
  (say *sandy* "sandy-1.wav")
  (say *navajo* "navajo-3.wav")
  (act *navajo* :leave)
  (act *sandy* :leave)
  (say *peach* "peach-1.wav")
  (say *peach* "peach-2.wav")
  (say *peach* "peach-3.wav")
  (say *peach* "peach-4.wav")
  (play-dialogue))


